version: '3.1'

services:

  db:
    image: postgres:11.5
    restart: always
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pixelvoid

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080